### PR TITLE
Update module import method

### PR DESCRIPTION
**Pull request by mattmcnabb**
Please review my changes to the module manifest and the module itself. I think this would provide an easier method for installation and importing. This would allow a simple copy-paste install to any module path. Thanks!

### CODE REVIEW

**Comment by mattmcnabb** [comment]
Only one further question - do you think this is worth a v0.2.3 tag? That way we can add new release notes with the new install instructions as well? Or would you rather do that later?

**Comment by JAL9302** [comment]
We'll be adding another github release for the same release we put on PS Gallery. Don't worry about that, we'll handle it.

**Comment by JAL9302** [comment]
Oops - github didn't notify me you added commits. Will look this weekend, thanks

**Comment by mattmcnabb** [comment]
👍 just happy to be contributing. Have a great weekend!

Sent while mobile

**Comment by JAL9302** [comment]
Hey Matt,

Looked over this. All the code looks good, but it looks like `Import-Module AzureAutomationAuthoringToolkit` now has to be run any time the PowerShell ISE is opened. Without these changes, `Install-AzureAutomationAuthoringToolkit` only has to be run once and then all subsequent PS ISE opens will just load the add on automatically. Given that, do we really think this is a good change to make? @eamonoreilly @alstab 

Wonder if there's some way to make the PowerShell ISE actually load the module on ISE start up. I guess that's what the ISE profile file (that the current way of loading the ISE add on uses) is for though...

**Comment by JAL9302** [comment]
Maybe we do a combination of the current way and the way proposed in this pull request? So we continue to update the ISE profile from Install/Uninstall-AzureAutomationISEAddon, but the line we add in the ISE profile is just `Import-Module AzureAutomationAuthoringToolkit`.

This would simplify the code as the pull request has done, but provide the same simplified user experience as the current way does.

**Comment by mattmcnabb** [comment]
I generally don't like modules that hijack your profile but that's just my opinion. I prefer to simply add the module to my module oath and run ipmo when I want it.

However you could definitely leave the install script for those who would use it.

Sent while mobile

-----Original Message-----

**Comment by JAL9302** [comment]
OK, want to modify your pull request to keep the install/uninstall cmdlets, and just make the content of the install cmdlet do ipmo? That way users can choose the profile way or manual way depending on what they like best.

**Comment by mattmcnabb** [comment]
I can do that, but it complicates the readme a bit. Should I bring back a section about persistent install to your profile?

**Comment by JAL9302** [comment]
I'll handle the readme, don't worry about that for now.

**Comment by mattmcnabb** [comment]
Sorry for the delay! The install and uninstall functions are back and added back to the module manifest as well.

**Comment by JAL9302** [comment]
Thanks Matt. I see $script:PowerShellToLoadAzureAutomationIseAddOnGeneric in AzureAutomationAuthoringToolkitInner.psm1 still has the old additions to the profile, where we load the DLL in the profile. But now this module loads the DLL itself, so all we have to do is import the module in the profile. Can you make that fix?

**Comment by mattmcnabb** [comment]
Sorry missed that. Fixed.

**Comment by JAL9302** [comment]
Don't think that change is correct...isn't this what we want?

$script:PowerShellToLoadAzureAutomationIseAddOnGeneric = @"
 `n
 # Start AzureAutomationISEAddOn snippet
 Import-Module AzureAutomationAuthoringToolkit
 # End AzureAutomationISEAddOn snippet
 "@

**Comment by mattmcnabb** [comment]
How about this?

``` Powershell
$script:PowerShellToLoadAzureAutomationIseAddOnGeneric = @"
`n
if(`$PSIse) {
    Import-Module AzureAutomationAuthoringToolkit
}
"@
```

Or do we want this automatic installation to extend to the console as well?

``` Powershell
$script:PowerShellToLoadAzureAutomationIseAddOnGeneric = @"
`n
    Import-Module AzureAutomationAuthoringToolkit
"@
```

**Comment by JAL9302** [comment]
I don't think we need the if PSISE part, since we are only adding to the ISE profile, which only ISE loads. Also, please keep the start and end comments, as those are needed for the uninstall ise add on cmdlet to know what to remove.

I hate to ask this, but any chance you can start from master again, and make the changes we decided to add? The diff on this currently seems to show a huge change in AzureAutomationAuthoringToolkitInner.psm1 (from when you removed and then added the install / uninstall stuff), making it hard for me to code review what was actually changed.

**Comment by mattmcnabb** [comment]
Ok, I was thinking the same thing - I felt like I was going the long way around. I have reverted back to master and then committed the following:
- Add dll as required assembly in the manifest
- Add the vertical add-on tool in the root module
- Change the text appended to the ISE profile to only import the module and nothing else

Only now I see a new problem  - the install function seems to copy a config file into the user's local profile. Is this really necessary? Couldn't the config file just reside in the module directory? Regardless, it seems the new importing philosophy won't work without further refactoring and that may be a bit beyond what you're looking for.

**Comment by JAL9302** [comment]
Thanks! Will look it over tomorrow.

Config file can't live in the module directory because then new module versions will cause a new config file to be used, instead of same one. And admin would be needed to write to the config file, since PSGet puts modules in an admin-only directory.

What if I just add to the readme that if you don't want to use Install-AzureAutomationIseAddOn to add it to your ISE profile, you also need to copy that file manually to your user profile directory once?

**Pull request closed without merging**
